# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__


class BamlAsyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlAsyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlAsyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser
    
    async def ChatWithLLM(self, messages: typing.List["types.MyUserMessage"],
        baml_options: BamlCallOptions = {},
    ) -> str:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.ChatWithLLM(messages=messages,
                baml_options=baml_options)
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(baml_options).call_function_async(function_name="ChatWithLLM", args={
                "messages": messages,
            })
            return typing.cast(str, result.cast_to(types, types, stream_types, False, __runtime__))
    async def ExtractLibrariesAndLanguages(self, description: str,
        baml_options: BamlCallOptions = {},
    ) -> types.LibrariesAndLanguages:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.ExtractLibrariesAndLanguages(description=description,
                baml_options=baml_options)
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(baml_options).call_function_async(function_name="ExtractLibrariesAndLanguages", args={
                "description": description,
            })
            return typing.cast(types.LibrariesAndLanguages, result.cast_to(types, types, stream_types, False, __runtime__))
    async def GetCompletion(self, message: str,
        baml_options: BamlCallOptions = {},
    ) -> str:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.GetCompletion(message=message,
                baml_options=baml_options)
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(baml_options).call_function_async(function_name="GetCompletion", args={
                "message": message,
            })
            return typing.cast(str, result.cast_to(types, types, stream_types, False, __runtime__))
    async def ToolCallOrMessage(self, message: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.Message", "types.GetWeatherAPI"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            stream = self.stream.ToolCallOrMessage(message=message,
                baml_options=baml_options)
            return await stream.get_final_response()
        else:
            # Original non-streaming code
            result = await self.__options.merge_options(baml_options).call_function_async(function_name="ToolCallOrMessage", args={
                "message": message,
            })
            return typing.cast(typing.Union["types.Message", "types.GetWeatherAPI"], result.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ChatWithLLM(self, messages: typing.List["types.MyUserMessage"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[str, str]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="ChatWithLLM", args={
            "messages": messages,
        })
        return baml_py.BamlStream[str, str](
          result,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractLibrariesAndLanguages(self, description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.LibrariesAndLanguages, types.LibrariesAndLanguages]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="ExtractLibrariesAndLanguages", args={
            "description": description,
        })
        return baml_py.BamlStream[stream_types.LibrariesAndLanguages, types.LibrariesAndLanguages](
          result,
          lambda x: typing.cast(stream_types.LibrariesAndLanguages, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.LibrariesAndLanguages, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def GetCompletion(self, message: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[str, str]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="GetCompletion", args={
            "message": message,
        })
        return baml_py.BamlStream[str, str](
          result,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ToolCallOrMessage(self, message: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[typing.Union["stream_types.Message", "stream_types.GetWeatherAPI"], typing.Union["types.Message", "types.GetWeatherAPI"]]:
        ctx, result = self.__options.merge_options(baml_options).create_async_stream(function_name="ToolCallOrMessage", args={
            "message": message,
        })
        return baml_py.BamlStream[typing.Union["stream_types.Message", "stream_types.GetWeatherAPI"], typing.Union["types.Message", "types.GetWeatherAPI"]](
          result,
          lambda x: typing.cast(typing.Union["stream_types.Message", "stream_types.GetWeatherAPI"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.Union["types.Message", "types.GetWeatherAPI"], x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def ChatWithLLM(self, messages: typing.List["types.MyUserMessage"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ChatWithLLM", args={
            "messages": messages,
        }, mode="request")
        return result
    async def ExtractLibrariesAndLanguages(self, description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractLibrariesAndLanguages", args={
            "description": description,
        }, mode="request")
        return result
    async def GetCompletion(self, message: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GetCompletion", args={
            "message": message,
        }, mode="request")
        return result
    async def ToolCallOrMessage(self, message: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ToolCallOrMessage", args={
            "message": message,
        }, mode="request")
        return result
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def ChatWithLLM(self, messages: typing.List["types.MyUserMessage"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ChatWithLLM", args={
            "messages": messages,
        }, mode="stream")
        return result
    async def ExtractLibrariesAndLanguages(self, description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractLibrariesAndLanguages", args={
            "description": description,
        }, mode="stream")
        return result
    async def GetCompletion(self, message: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GetCompletion", args={
            "message": message,
        }, mode="stream")
        return result
    async def ToolCallOrMessage(self, message: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ToolCallOrMessage", args={
            "message": message,
        }, mode="stream")
        return result
    

b = BamlAsyncClient(DoNotUseDirectlyCallManager({}))