# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.GetWeatherAPI": types.GetWeatherAPI,
    "stream_types.GetWeatherAPI": stream_types.GetWeatherAPI,

    "types.LibrariesAndLanguages": types.LibrariesAndLanguages,
    "stream_types.LibrariesAndLanguages": stream_types.LibrariesAndLanguages,

    "types.Message": types.Message,
    "stream_types.Message": stream_types.Message,

    "types.MyUserMessage": types.MyUserMessage,
    "stream_types.MyUserMessage": stream_types.MyUserMessage,


}